Repository Zoinkwiz/clue-details, pull requests merged in 2025-03, with the labels that each got.

#102 Implemented inventory tags for clue scrolls and clue items
  README.md
  src/main/java/com/cluedetails/ClueDetailsConfig.java
  src/main/java/com/cluedetails/ClueDetailsItemsOverlay.java
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
Labels: enhancement

#104 Improved sidebar popup menu behavior
  src/main/java/com/cluedetails/panels/ClueDetailsParentPanel.java
Labels: enhancement

#105 Easy->Elite Ground Clues Overlay
  README.md
  src/main/java/com/cluedetails/ClueDetailsConfig.java
  src/main/java/com/cluedetails/ClueDetailsItemsOverlay.java
  src/main/java/com/cluedetails/ClueDetailsTagsOverlay.java
  src/main/java/com/cluedetails/ClueGroundManager.java
  src/main/java/com/cluedetails/ClueGroundOverlay.java
  src/main/java/com/cluedetails/ClueInstance.java
  src/main/java/com/cluedetails/Clues.java
Labels: enhancement

#107 Small Clue Ground Timers fixes
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/ClueGroundTimer.java
Labels: bug

#111 Remove superfluous warnings; Add warning for ground clue timers
  build.gradle
  src/main/java/com/cluedetails/ClueDetailsConfig.java
Labels: bug

#115 fix: clue timers notifications use shouldNotify
  build.gradle
  src/main/java/com/cluedetails/ClueDetailsConfig.java
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/ClueGroundTimer.java
Labels: bug

#117 Cache filteredClues list
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/Clues.java
Labels: enhancement

#120 fix/inventory-overlay
  src/main/java/com/cluedetails/ClueBankManager.java
  src/main/java/com/cluedetails/ClueDetailsInventoryOverlay.java
  src/main/java/com/cluedetails/ClueDetailsItemsOverlay.java
  src/main/java/com/cluedetails/ClueDetailsOverlay.java
  src/main/java/com/cluedetails/ClueDetailsTagsOverlay.java
  src/main/java/com/cluedetails/ClueGroundManager.java
  src/main/java/com/cluedetails/ClueInventoryManager.java
Labels: bug

#118 fix: Improvements on ground item tracking
  src/main/java/com/cluedetails/ClueBankManager.java
  src/main/java/com/cluedetails/ClueDetailsInventoryOverlay.java
  src/main/java/com/cluedetails/ClueDetailsItemsOverlay.java
  src/main/java/com/cluedetails/ClueDetailsOverlay.java
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/ClueDetailsTagsOverlay.java
  src/main/java/com/cluedetails/ClueGroundManager.java
  src/main/java/com/cluedetails/ClueGroundOverlay.java
  src/main/java/com/cluedetails/ClueGroundSaveDataManager.java
  src/main/java/com/cluedetails/ClueGroundTimer.java
  src/main/java/com/cluedetails/ClueInstance.java
  src/main/java/com/cluedetails/ClueInventoryManager.java
  src/main/java/com/cluedetails/Clues.java
  src/main/java/com/cluedetails/WorldPointToClueInstances.java
Labels: bug, enhancement

#119 Cache clues in maps instead of a list for faster lookups
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/Clues.java
Labels: bug

#122 fix: ClueGroundTimer cleanup; Add renotification
  src/main/java/com/cluedetails/ClueDetailsConfig.java
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/ClueGroundOverlay.java
  src/main/java/com/cluedetails/ClueGroundTimer.java
Labels: bug, enhancement

#123 fix: Add check for if clue being added to inventory store is a clue
  src/main/java/com/cluedetails/ClueInventoryManager.java
Labels: bug

#126 fix: Ground Items collapse conflicts
  src/main/java/com/cluedetails/ClueDetailsOverlay.java
  src/main/java/com/cluedetails/ClueInstance.java
Labels: bug
