Repository Zoinkwiz/clue-details, pull requests merged in 2025-04, with the labels that each got.

#124 fix: invalidate clue items cache on new beginner or master clue
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/ClueInventoryManager.java
Labels: bug

#129 feat: Three-stepper saving
  src/main/java/com/cluedetails/ClueDetailsConfig.java
  src/main/java/com/cluedetails/ClueDetailsItemsOverlay.java
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/ClueGroundOverlay.java
  src/main/java/com/cluedetails/ClueInstance.java
  src/main/java/com/cluedetails/ClueThreeStepSaver.java
  src/main/java/com/cluedetails/ClueThreeStepSaverWidgetOverlay.java
Labels: enhancement

#128 2.3.3 Cleanup
  src/main/java/com/cluedetails/ClueDetailsOverlay.java
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/ClueGroundManager.java
  src/main/java/com/cluedetails/ClueInstance.java
  src/main/java/com/cluedetails/ClueInventoryManager.java
Labels: bug

#131 fix: Cleanup for instantiation of managers and overlays
  src/main/java/com/cluedetails/ClueBankManager.java
  src/main/java/com/cluedetails/ClueBankSaveDataManager.java
  src/main/java/com/cluedetails/ClueDetailsInventoryOverlay.java
  src/main/java/com/cluedetails/ClueDetailsItemsOverlay.java
  src/main/java/com/cluedetails/ClueDetailsOverlay.java
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/ClueDetailsTagsOverlay.java
  src/main/java/com/cluedetails/ClueDetailsWidgetsOverlay.java
  src/main/java/com/cluedetails/ClueGroundManager.java
  src/main/java/com/cluedetails/ClueGroundOverlay.java
  src/main/java/com/cluedetails/ClueGroundSaveDataManager.java
  src/main/java/com/cluedetails/ClueInventoryManager.java
  src/main/java/com/cluedetails/CluePreferenceManager.java
  src/main/java/com/cluedetails/ClueThreeStepSaver.java
  src/main/java/com/cluedetails/ClueThreeStepSaverWidgetOverlay.java
  src/main/java/com/cluedetails/ClueWidgetManager.java
  src/main/java/com/cluedetails/Clues.java
Labels: bug, enhancement
