Repository Zoinkwiz/clue-details, pull requests merged in 2025-05, with the labels that each got.

#140 fix: Remember beginner/master clues when traversing planes
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/ClueGroundManager.java
Labels: bug, help wanted

#139 fix: Clear ground clues on restart
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/ClueGroundManager.java
  src/main/java/com/cluedetails/WorldPointToClueInstances.java
Labels: bug

#147 fix: Avoid duping clues when entering clue area
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/ClueGroundManager.java
Labels: bug

#134 feat: Identify Charlie & Falo clues from dialogue
  src/main/java/com/cluedetails/BeginnerMasterClueText.java
  src/main/java/com/cluedetails/ClueInventoryManager.java
Labels: enhancement

#141 feat: Use tier name for unidentified ground clues overlay
  src/main/java/com/cluedetails/ClueInstance.java
Labels: enhancement

#143 fix: Overwrite description
  src/main/java/com/cluedetails/ClueDetailsConfig.java
Labels: bug

#144 fix: three-step cryptic submenu order
  src/main/java/com/cluedetails/ClueDetailsOverlay.java
Labels: bug

#145 feat: Reverse ground clues overlay
  src/main/java/com/cluedetails/ClueDetailsConfig.java
  src/main/java/com/cluedetails/ClueGroundOverlay.java
Labels: enhancement

#148 fix gson usage
  src/main/java/com/cluedetails/ClueDetailsSharingManager.java
Labels: bug
