Repository Zoinkwiz/clue-details, pull requests merged in 2025-01, with the labels that each got.

#75 2.1.1: Separate text and colors export; fix beginner/master colors
  README.md
  build.gradle
  src/main/java/com/cluedetails/ClueDetailsConfig.java
  src/main/java/com/cluedetails/ClueDetailsOverlay.java
  src/main/java/com/cluedetails/ClueDetailsSharingManager.java
  src/main/java/com/cluedetails/ClueDetailsTagsOverlay.java
  src/main/java/com/cluedetails/ClueInstance.java
  src/main/java/com/cluedetails/ThreeStepCrypticClue.java
  src/main/java/com/cluedetails/panels/ClueDetailsParentPanel.java
Labels: bug, enhancement

#76 Ability to disable Clue Details per clue tier
  src/main/java/com/cluedetails/ClueDetailsConfig.java
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/ClueDetailsTagsOverlay.java
  src/main/java/com/cluedetails/ClueDetailsWidgetOverlay.java
  src/main/java/com/cluedetails/ClueInventoryManager.java
  src/main/java/com/cluedetails/Clues.java
Labels: enhancement

#83 Ground Clues Overlay for Beginner & Master Clues
  README.md
  src/main/java/com/cluedetails/ClueDetailsConfig.java
  src/main/java/com/cluedetails/ClueDetailsOverlay.java
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/ClueGroundOverlay.java
  src/main/java/com/cluedetails/ClueInstance.java
  src/main/java/com/cluedetails/ClueInventoryManager.java
Labels: enhancement

#85 Add edit color and item to all clues
  README.md
  src/main/java/com/cluedetails/ClueDetailsWidgetOverlay.java
  src/main/java/com/cluedetails/ClueInventoryManager.java
Labels: enhancement

#90 Ground item menu color fix
  src/main/java/com/cluedetails/ClueDetailsOverlay.java
Labels: bug

#89 Three-step cryptic hover text
  src/main/java/com/cluedetails/ClueDetailsOverlay.java
Labels: enhancement

#88 Ground Item Pattern Cleanup
  src/main/java/com/cluedetails/ClueDetailsOverlay.java
Labels: bug
