Repository Zoinkwiz/clue-details, pull requests merged in 2025-06, with the labels that each got.

#150 Allow highlighting widgets with "Continue" option and no actions
  src/main/java/com/cluedetails/ClueWidgetManager.java
Labels: bug, enhancement

#151 fix: 2846 Ardougne Zoo challenge answer
  src/main/java/com/cluedetails/Clues.java
Labels: bug

#152 fix: Clue Instance despawn time tracking
  src/main/java/com/cluedetails/ClueBankManager.java
  src/main/java/com/cluedetails/ClueBankSaveDataManager.java
  src/main/java/com/cluedetails/ClueDetailsPlugin.java
  src/main/java/com/cluedetails/ClueGroundManager.java
  src/main/java/com/cluedetails/ClueGroundOverlay.java
  src/main/java/com/cluedetails/ClueGroundSaveDataManager.java
  src/main/java/com/cluedetails/ClueInstance.java
  src/main/java/com/cluedetails/ClueInstanceData.java
  src/main/java/com/cluedetails/WorldPointToClueInstances.java
Labels: bug

#154 fix: Sidebar filter dropdowns match config
  src/main/java/com/cluedetails/panels/ClueDetailsParentPanel.java
Labels: bug, sidebar
